### ISSUE TITLE
Metadata quality

### ISSUE THREAD

**Issue by p1d1d1** [FHNW-IVGI/Geoharvester#101]
@314a @FStriewski @eliaferrari "Metadata quality" really needs a lot of love!

e.g. set the Service to "KT_BE":

- the fields "abstract", "keywords" and "metadata" all contain the text "nan". Neverthless the metadata quality value is "100"!

We really need to discuss this.

**Comment by eliaferrari** [comment]
@p1d1d1 thank you for pointing this out.
With the last merge an old bug has been introduced and the metadata quality score has been inverted.
I've corrected this issue here: https://github.com/FHNW-IVGI/Geoharvester/blob/af9917d99752da910657c2f515ef0df24be3d03e/scraper/utils.py#L645
We will reprocess the last new data to have the corrected metadata quality score.

**Comment by p1d1d1** [comment]
@eliaferrari thanks for the info. Please let me know when it is deployed so that I can continue my tests.
I still think that we will need to finetune it in the future.
